### ISSUE TITLE
Pipeline uploading full model after first run

### ISSUE THREAD

**Issue by paulcjh** [mystic-ai/pipeline#35]
Once a pipeline that contains a model has been run, the full initialised model is then uploaded. This is particularly inconvenient for huggingface transformer models.

Example:
```python
with Pipeline("HF pipeline") as builder:
    input_str = Variable(str, is_input=True)
    builder.add_variables(input_str)

    hf_model = TransformersModelForCausalLM(
        model_path="EleutherAI/gpt-neo-125M",
        tokenizer_path="EleutherAI/gpt-neo-125M",
    )

    output_str = hf_model.predict(input_str)

    builder.output(output_str)

output_pipeline = Pipeline.get_pipeline("HF pipeline")

# Run the model
output_pipeline.run("Hello there")

print("Now uploading GPTNeo pipeline")
# The next line will upload the full 1GB model
uploaded_pipeline = api.upload_pipeline(output_pipeline)```

**Comment by alexpearce** [comment]
Rather than uploading whatever object is passed to `upload_pipeline` we could check whether it is an instance or not. AFAIK only the _class_ is needed rather than the instance; the builder knows the `__init__` arguments so can take the class, re-initialise it on the server, and then call the load/predict functions. (This does assume the user calls no other instance methods, e.g. `hf_model.some_other_method()`, which mutate `self`.)

To [extract the class from an instance](https://stackoverflow.com/a/395782):

```python
import inspect


def class_from_object(instance_or_class):
    if inspect.isclass(instance_or_class):
        return instance_or_class
    else:
        return type(instance_or_class)
```

**Comment by paulcjh** [comment]
Sounds good - we can try this out post API v1 migration. I guarantee people will upload after a local run so this will def have to be in there post public launch.
